name: contraflutterkit
description: Flutter application built on top of contra wireframe kit.


version: 1.0.0+1


environment:
  sdk: ">=2.2.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
  uses-material-design: true

